version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: cidadagil_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cidadagil_network

volumes:
  postgres_data:

networks:
  cidadagil_network:
    driver: bridge
